name: .Net Restore, Build, Tests and Publish NuGet Package

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./FG.FFTT.Api.Client
    - name: Build
      run: dotnet build --configuration Release --no-restore ./FG.FFTT.Api.Client
    - name: Tests
      env:
        APP_ID: ${{ secrets.APP_ID }}
        APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        APP_SERIAL_NUMBER: ${{ secrets.APP_SERIAL_NUMBER }}
      run: dotnet test --configuration Release --no-build --verbosity normal ./FG.FFTT.Api.Client
    - name: Create the package
      run: dotnet pack --configuration Release ./FG.FFTT.Api.Client --include-symbols
    - name: Publish the package
      run: dotnet nuget push ./FG.FFTT.Api.Client/bin/Release/*.nupkg -k ${{secrets.NUGETAPIKEY}} -s https://api.nuget.org/v3/index.json
